version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: ["bash", "/src/gencert.sh"]
    ports:
      - "4443:4443"
    networks:
      - tlslab
    privileged: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    command: ["bash", "client.sh"]
    environment:
      TARGET_HOST: server
      TARGET_PORT: 4443
      LOOPS: 5000
    depends_on:
      - server
    networks:
      - tlslab
    privileged: true

networks:
  tlslab:
    driver: bridge
